### ISSUE TITLE
MagpieRSS used to generate index.html does not work with PHP8

### ISSUE THREAD

**Issue by wsfulton** [swig/www#14]
Given SWIG has dropped support for PHP7 in swig-4.2.0 and testing is now done with PHP8, we need to update the website generation for PHP8 too.

The index.html file is generated by running:
```
make updateweb
```
which simply runs:
```
python makeweb.py
```
One of the steps it does is generate index.php from index.ph, then index.html is more or less generated by running:
```
php index.php > index.html
```
This final step fails with PHP8 and does not give any errors. 

Some php expertise would be much appreciated to provide a fix. Alternatively perhaps replace this all with something completely different or replace magpierss (which hasn't been maintained for a decade with something else like simplepie [simplepie comparisons](http://simplepie.org/wiki/faq/why_would_i_use_simplepie_over_something_else).

**Comment by ojwb** [comment]
Definitely seems better to stop using something which hasn't been maintained for a decade (or since 2006 if the simplepie website is to be believed).

Do we even need something dynamic though?  Our website doesn't update often so it seems we could statically generate the RSS when the site is updated.

**Comment by wsfulton** [comment]
98ccff738c7dc3a4e1e6c700467799bc82496cff made the change to grab the RSS feed and create a static index.html file containing the news from the RSS feed. The makeweb.py changes in that commit effectively does the invocation:
```
php index.php > index.html
```
This is the script that needs updating to work with php 8. Continuing to generate static html files is fine I think.

**Comment by wsfulton** [comment]
>  Our website doesn't update often so it seems we could statically generate the RSS when the site is updated.

I've interpreted this as generating HTML as I'm not sure what you mean by generate RSS as there isn't an RSS generation. The RSS newsfeed is maintained by SourceForge.

So to be clear, the current workflow is, update the newsfeed on SourceForge, then run the scripts to update the web site, which grabs the latest from the newsfeed. I don't see how that can change though, unless we drop the newsfeed, which I don't see as a good option when this can all be solved by updating the code that talks to the newsfeed.
