### ISSUE TITLE
if possible, make Doc3.0 not Doc1.3 shown in google searches

### ISSUE THREAD

**Issue by wojdyr** [swig/www#5]
When googling results in SWIG documentation, it's always (at least for me) only version 1.3.
For example:
https://www.google.co.uk/search?q=swig+python
gives
www.swig.org/Doc1.3/Python.htm

Apparently google considers versions 1.3, 2.0 and 3.0 too similar to show them all, but there must be a way to hint which version is the preferred one. Which would be the latest one?

**Comment by ojwb** [comment]
There's already a ticket about this: https://github.com/swig/swig/issues/428

I did suggest a solution there, but people seemed rather negative about it and I didn't try to push it through.

The other ticket is really against the wrong repo, but has extensive discussion.  Sadly github's ticket system appears to be too primitive to support reassigning a ticket to another repo, but having two tickets open doesn't seem useful, so I guess this is the one to close as a duplicate.
