### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by thorade** [swig/www#6]
The page
http://www.swig.org/tutorial.html
has a link to
`http://www.southern-storm.com.au/portable_net.html`
but that page does no longer contain any helpful content.

(Link as code, because I did not want to link there again).

**Comment by thorade** [comment]
Source is here:
https://github.com/swig/www/blob/master/tutorial.ht

**Comment by wsfulton** [comment]
I've updated the tutorial now, hope that helps.

**Comment by thorade** [comment]
Thanks
